// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykmegrxauvwpzcbjyisf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbWVncnhhdXZ3cHpjYmp5aXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1OTgwMzgsImV4cCI6MjA4MjE3NDAzOH0.tiK_KkeHf-Hm7s8KSLppALmYIxHAyzy7y4R7Ygn_yE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});